### ISSUE TITLE
package requirements 

### ISSUE THREAD

**Issue by chunzhu** [ozanarkancan/char-ner#1]
Hi,

is it possible to share what are the library package requirements that you use to run this package?

i am pretty new to running people's codes. i have been trying to run your codes, but i cant run it successfully.

first there was issue with theano version unable to locate downsample, after which i downgraded to 0..
next, it produced  ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 62 and outputs = 1) which through some google it shows it has to do with numpy version.
then i downgraded to 1.8.0 numpy and it produces ValueError: ('The following error happened while compiling the node', forall_inplace,cpu,scan_fn}(Elemwise{minimum,no_inplace}.0, Elemwise{sub,no_inplace}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, IncSubtensor{InplaceSet;:int64:}.0, Join.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{x,0}.0), '\n', 'numpy.dtype has the wrong size, try recompiling')

Hopefully you can share with me the package requirements so i can run this successfully. Thanks!

**Comment by ozanarkancan** [comment]
Hi,

We are using [anaconda](https://www.continuum.io/downloads) for scientific packages. In addition to the packages in anaconda, you need to install [Lasagne](http://lasagne.readthedocs.io/en/latest/) . In any case, here is the list of packages:

Lasagne                   0.2.dev1
numpy                     1.11.2
scipy                     0.18.1
scikit-learn              0.17.1
tabulate                  0.7.5
Theano                    0.8.2

**Comment by chunzhu** [comment]
Thanks a lot Ozanarkancan!

That helps, my machine is learning now. Next step is to play with the learned model
