### ISSUE TITLE
No such file error

### ISSUE THREAD

**Issue by MehmedGIT** [ozanarkancan/char-ner#3]
I am getting the following error when trying to run the example command. What is going wrong here ? 

$ python src/exper.py --activation bi-lstm --n_hidden 128 128 --drates .2 .5 .8 --lang cze
Traceback (most recent call last):
  File "src/exper.py", line 238, in <module>
    main()
  File "src/exper.py", line 221, in main
    setup_logger(args)
  File "src/exper.py", line 208, in setup_logger
    ihandler = logging.FileHandler('{}/{}.info'.format(LOG_DIR,base_log_name), mode='w')
  File "/home/sdn/anaconda3/envs/my_env_deep27/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/sdn/anaconda3/envs/my_env_deep27/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/sdn/Desktop/char-ner/logs/onos-p4-dev-vm:cpu,activation:bi-lstm,n_hidden:128,128,fbmerge:concat,drates:0.2,0.5,0.8,recout:0,opt:adam,lr:0.001,norm:1,gclip:0,truncate:-1,n_batch:32,shuf:1,captrn:500,emb:0,lang:cze,fbias:0.0.info'

**Comment by ozanarkancan** [comment]
The path of default log file name is generated from arguments and its location is "char-ner/logs/". You should create the "logs" folder under the char-ner repo.

The generated file name for your attempt was:
'**/home/sdn/Desktop/char-ner/logs**/onos-p4-dev-vm:cpu,activation:bi-lstm,n_hidden:128,128,fbmerge:concat,drates:0.2,0.5,0.8,recout:0,opt:adam,lr:0.001,norm:1,gclip:0,truncate:-1,n_batch:32,shuf:1,captrn:500,emb:0,lang:cze,fbias:0.0.info'

**Comment by MehmedGIT** [comment]
Creating "logs" folder worked out. I think this should be mentioned in the Readme file. 

Everything seems to work fine so far while training the model. Thanks!!

**Comment by ozanarkancan** [comment]
Cool! I will update the README. I am closing this issue.
