### ISSUE TITLE
Data Files

### ISSUE THREAD

**Issue by sonali856** [ozanarkancan/char-ner#5]
Hi, 
I found your paper interesting and I am trying to implement the same for english CoNLL 2003 dataset, is there any kind of preprocessing required for the data? Is it possible for you to provide the other languages datasets also which have been used for the paper.

**Comment by ozanarkancan** [comment]
Hi,

Thank you for your interest. I think we published all datasets that have no license issue. Only preprocessing step is transforming data to the CONLL format. After that, by default, we map a character to a unique id. But one can try different type of mappings (e.g. mapping all digits into single digit representation). You can check out the [featchar](https://github.com/ozanarkancan/char-ner/blob/master/src/featchar.py) module.
